# Generated by Django 5.2.6 on 2025-09-30 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='university',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='General', help_text='e.g., Starters, Main Course, Beverages', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='options',
            field=models.JSONField(blank=True, help_text="e.g., [{'name': 'Extra Cheese', 'price': 10.00 , 'default' : true}]", null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='domain',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='A short, catchy description of the vendor.')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('vendor_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('DHABA', 'Dhaba'), ('STALL', 'Small Stall'), ('BRAND', "Big Brand (e.g., Domino's)")], default='STALL', max_length=20)),
                ('dietary_focus', models.CharField(choices=[('VEG_ONLY', 'Pure Veg'), ('NON_VEG', 'Non-Veg Available'), ('BOTH', 'Veg & Non-Veg')], default='BOTH', max_length=20)),
                ('offers_delivery', models.BooleanField(default=False)),
                ('offers_takeaway', models.BooleanField(default=True)),
                ('has_seating', models.BooleanField(default=False)),
                ('is_delivering_now', models.BooleanField(default=False, help_text='Can be toggled by the vendor.')),
                ('current_orders', models.PositiveIntegerField(default=0, help_text='Current number of active orders.')),
                ('max_orders', models.PositiveIntegerField(default=10, help_text='Max orders they can handle at once.')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.vendor'),
        ),
        migrations.AddField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendor'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('vendor__isnull', False), ('item__isnull', False), _connector='OR'), name='review_must_be_for_vendor_or_item'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
